name: Foundry CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive # THIS IS THE LINE FOUNDRY FORGOT

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build Contracts
        run: forge build --sizes

      - name: Run Tests
        run: forge test
